version: '3'

services:
  hub:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2g'

  seleniumstudy:
    build: .
    environment:
      HUB_HOST: "hub"
      HUB_PORT: 4444
      BROWSER_NAME: Firefox
      PAGE_URL: https://www.wikipedia.org/
    depends_on:
      - hub
    entrypoint: mvn test -PRegression